clear a b bayestopt_ calfa cbeta cf cfc cg cgy chabb cindp cindw clandaw cmap cmaw ...
    constebeta constelab constepinf cprobp cprobw crdy crhoa crhoas crhob crhog crhols ...
    crhoms crhopinf crhoqs crhow crpi crr cry csadjcost csigl csigma ctou ctrend curvp ...
    curvw czcap dataset_ dataset_info emptydatesobject emptydseriesobject epinfma estim_params_ ...
    estimation_info ewma ex0_ g info invef k kf kp kpf labf mc ms oo_ options_ path pk pkf ...
    qs rk rkf rrf spinf sw tic0 var_list_ wf yf ys0_ zcap zcapf y r w lab inve pinf c ...
    data_raw decision M_ z_ext sigma_a sigma_b sigma_g sigma_m sigma_nu_ext sigma_pinf sigma_qs sigma_w alpha_ext
